sudo: required
services:
  - docker
before_install:
  - openssl aes-256-cbc -K $encrypted_0c35eebf403c_key -iv $encrypted_0c35eebf403c_iv -in service-account.json.enc -out service-account.json -d
  
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  # download google cloud | install locally on travis.ci
  - source $HOME/google-cloud-sdk/path.bash.inc
  # source file path.bash.inc, add some configuration to travis for googlecloud setup
  - gcloud components update kubectl
  # update a kubectl to our travis environment
  - gcloud auth activate-service-account --key-file service-account.json
  # authenticate our access to google Cloud
